setup:
  seed: 3
  use_gpu: False
  
train:
  name: 'LunarLanderContinuous-v2'
  n_episodes: 1001
  verbose: 50
  
  baseline: True

agent:
  gamma: 0.99
  std: 1

  dnn:
    h_layers: 2
    h_size: 64
    lr: 1e-4
    print_model: False
